ChatApp/ChatApp/Controllers/ClassesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Model;
using FormsAuthenticationExtensions;
using System.Web.Security;
using System.Data.SqlClient;
using System.Data.Entity.Infrastructure;
using ChatApp.Filter;

namespace ChatApp.Controllers
    {
    [Authorize]
    [NitishAuthentication]
    public class ClassesController : Controller
    {
        private ChatAppContext db = new ChatAppContext();


        // GET: Classes
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var classes = db.Classes.Include(u => u.University);
            foreach (var item in classes.ToList())
            {
                item.MemberCount = item.Users.Count;
            }
            return View(classes.ToList());
        }



        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Class @class = db.Classes.Find(id);
            if (@class == null)
            {
                return HttpNotFound();
            }
            return View(@class);
        }

        //// GET: Classes/Create
        //public ActionResult Create()
        //{
        //    ViewBag.UniversityId = new SelectList(db.Universities, "ID", "UniversityTitle");
        //    return View();
        //}

        //// POST: Classes/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ID,Title,MemberCount,Semester,AccessCode,AdminInfo,ProfileImage,UniversityId")] Model.Class @class)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            db.Classes.Add(@class);
        //            db.SaveChanges();
        //            return RedirectToAction("Index");
        //        }
        //        catch (Exception)
        //        {
        //           /////?????????????????????????????????????????????????/
        //            throw;
        //        }

        //    }

        //    ViewBag.UniversityId = new SelectList(db.Universities, "ID", "UniversityTitle", @class.UniversityId);
        //    return View(@class);
        //}
        [Authorize(Roles = "Admin,Professor")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Class @class = db.Classes.Find(id);
            if (@class == null)
            {
                return HttpNotFound();
            }
            ViewBag.UniversityId = new SelectList(db.Universities, "ID", "UniversityTitle", @class.UniversityId);
            return View(@class);
        }

        // POST: Classes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,MemberCount,Semester,AccessCode,AdminInfo,ProfileImage,UniversityId")] Class @class)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@class).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UniversityId = new SelectList(db.Universities, "ID", "UniversityTitle", @class.UniversityId);
            return View(@class);
        }

        //ابن اکشن مستقیم توسط استاد  صدا زده نمیشود.بلکه هر استاد برای حذف کلاسش میتواند از آن لفت دهد
        //به این ترتیب با لفت دادن ادمین کلاس حذف خواهد شد
        //پس فقط توسط اذمین صدا زده میشود
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Class @class = db.Classes.Find(id);
            if (@class == null)
            {
                return HttpNotFound();
            }
            return View(@class);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Class @class = db.Classes.Find(id);
            db.Classes.Remove(@class);
            db.SaveChanges();
            return RedirectToAction("Index");
        }





        //*****************************************************
        //*****************************************************




        public ActionResult MyClasses()
        {   //Goal:show ether "CreationClassPage " or "JoinClassPage " To the User,Depend on What is his Role ?!
            var ticketData = ((FormsIdentity)HttpContext.User.Identity).Ticket.GetStructuredUserData();
                  //  ViewBag.UserID = ticketData["UserID"];          
            //Note: ROleID for Students:1012   &   ROleID for Proffesors:1011
            ViewBag.UserRoleId =int.Parse(ticketData["UserRoleId"]);


            string userid = ticketData["UserID"];
            User u = FindUserById(Guid.Parse(userid));
            var UserClassList = u.Classes;
            

            return View(UserClassList);
        }
       
       public JsonResult LeftClass()
        {
            int id = Int32.Parse(Request["id"]);
           
            var ticketData = ((FormsIdentity)HttpContext.User.Identity).Ticket.GetStructuredUserData();
            string userid = ticketData["UserID"];
            User u = FindUserById(Guid.Parse(userid));
            Class c = FindClassById(id);

            //if the User is admin of class(=Professor) ,then Class must DESTROY at all 

            if (c.AdminInfo==u.Username)
            {
                db.Classes.Remove(c);
                db.SaveChanges();
            }
            else
            {
                //he is just a student:
                u.Classes.Remove(c);
                db.SaveChanges();
            }



            
           
          
            return Json(true, JsonRequestBehavior.AllowGet);
         //   Redirect(Request.UrlReferrer.ToString());

        }

        [Authorize(Roles = "Admin,Professor")]
        public ActionResult FindUniversity()
        {
            ViewBag.UniversityId = new SelectList(db.Universities, "ID", "UniversityTitle");
            return View();
            
        }
        [Authorize(Roles = "Admin,Professor")]
        public ActionResult CreateClass()
        {
            return View();
        }


        [Authorize(Roles = "Admin,Professor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateClass([Bind(Include = "ID,Title,MemberCount,Semester,AccessCode,AdminInfo,ProfileImage,UniversityId")] Class @class)
        {


            if (ModelState.IsValid)
            {
                var ticketData = ((FormsIdentity)HttpContext.User.Identity).Ticket.GetStructuredUserData();
                string userid = ticketData["UserID"];
                User u = FindUserById(Guid.Parse(userid));

               
                    @class.AdminInfo = u.Username;
                    @class.MemberCount = 0;
                    db.Classes.Add(@class);
                    
                    //add the creator(=professor) as one member :
                    @class.Users.Add(u);
                    @class.MemberCount++;
                //complete AdminInfo Column whit creator(=professor) Username :
                try
                {
                    db.SaveChanges();
                    //var c = FindClassByTitleAndAdmin(@class.Title, @class.AdminInfo);
                    ViewBag.ClassId = @class.ID;
                    return View("ClassSuccesfullyCreated");

                }


                catch (DbUpdateException e)
                {
                    var sqlException = e.GetBaseException() as SqlException;
                    //2601 is error number of unique index violation
                    if (sqlException != null && sqlException.Number == 2601)
                    {
                        //Unique index was violated. Show corresponding error message to user:
                        ModelState.AddModelError("AccessCode", "این کد قبلا برای کلاس دیگری رزرو شده است. لطفا کدورود  دیگری برای کلاس خود انتخاب کنید");
                    }
                }

            }

            ViewBag.UniversityId = new SelectList(db.Universities, "ID", "UniversityTitle", @class.UniversityId);
            return View(@class);
        }





        public Class FindClassById(int? id)
        {
            if (id == null)           
                  return null;
            
            Class @class = db.Classes.Find(id);

            if (@class == null)          
                return null;
            

            return @class;

        }

        public User FindUserById(Guid id)
        {
            if (id == null)
                return null;

            User u= db.Users.Find(id);

            if (u== null)
                return null;


            return u;

        }

        public Class FindClassByTitleAndAdmin(string title,string adminUsername)
        {

ChatApp/ChatApp/Views/Classes/ClassSuccesfullyCreated.cshtml
<div class="jumbotron">
    <hr />

    <div style="align-content:center">

        <h2 class="success">
            @Resources.ClassRF.ClassSuccessfulyCreated
        </h2>


    </div>
    @{
        int ClassIdretrive =@ViewBag.ClassId;
    }
    <hr />
    <hr />

    <div class="row">
        <div class="col-md-5">
            @Html.ActionLink(@Resources.ClassRF.OpenClass, "MyClass", new { classID = ClassIdretrive }, new { @class = "btn btn-success col-md-5" })

        </div>

        <div class="col-md-5" style="align-items:center">
            <p><a class="btn btn-success col-md-5" href="https://localhost:44355/Classes/MyClasses">@Resources.ClassRF.SeeAllClass</a></p>
        </div>

    </div>



</div>

ChatApp/ChatApp/Views/Classes/ClassSuccessful.cshtml
<div class="jumbotron">
    <hr />

    <div style="align-content:center">

        <h2 class="success">
            your Class Successfully Created!
        </h2>


    </div>
    
    <hr />
    <hr />

    <div class="row">
        <spa class="col-md-5" style="align-content:center">
            <p><a class="btn btn-success col-md-5" href="#">Go TO Class!</a></p>
        </spa>

        <div class="col-md-5" style="align-items:center">
            <p><a class="btn btn-success col-md-5" href="https://localhost:44355/Classes/SearchAllUserClasses">See All My Class</a></p>
        </div>

    </div>
   


</div>

ChatApp/ChatApp/Views/Classes/Create.cshtml
@model Model.Class

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Class</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MemberCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MemberCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MemberCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Semester, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Semester, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Semester, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccessCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccessCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccessCode, "", new { @class = "text-danger" })
            </div>
        </div>
        z
        <div class="form-group">
            @Html.LabelFor(model => model.AdminInfo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdminInfo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdminInfo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfileImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProfileImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProfileImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UniversityId, "UniversityId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UniversityId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UniversityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ChatApp/ChatApp/Views/Classes/CreateClass.cshtml
@model Model.Class

@{
    ViewBag.Title =Resources.ClassRF.CreatTitle;
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Class</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })




    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2 necessaryField" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>




<div class="form-group">
    @Html.LabelFor(model => model.Semester, htmlAttributes: new { @class = "control-label col-md-2 necessaryField" })
    <div class="col-md-10">
        @Html.EnumDropDownListFor(m => m.Semester, "Select a Item", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Semester, "", new { @class = "text-danger" })

    </div>
</div>


    @*<div class="form-group">
            @Html.LabelFor(model => model.ProfileImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProfileImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProfileImage, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <hr />
    <hr />

    <div class="form-group">
        @Html.LabelFor(model => model.AccessCode, htmlAttributes: new { @class = "control-label col-md-2 necessaryField" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AccessCode, new { htmlAttributes = new { @class = "form-control col-md-2" } })
            <br />
            <div>
                @Html.ValidationMessageFor(model => model.AccessCode, "", new { @class = "text-danger col-md-11" })

            </div>
        </div>
    </div>
  
    <div class="container">
        <div class="col-md-3">

        </div>
        <div class="col-md-8">
            <br />
            <input type="submit" value="@Resources.ClassRF.Create_btn" class="btn btn-default btn-success" width="100"/>
        </div>
    </div>
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ChatApp/ChatApp/Views/Classes/Delete.cshtml
@model Model.Class

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Class</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.University.UniversityTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.University.UniversityTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MemberCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MemberCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Semester)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Semester)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccessCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccessCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdminInfo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdminInfo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfileImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfileImage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ChatApp/ChatApp/Views/Classes/Details.cshtml
@model Model.Class

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Class</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.University.UniversityTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.University.UniversityTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MemberCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MemberCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Semester)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Semester)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccessCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccessCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AdminInfo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AdminInfo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfileImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfileImage)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ChatApp/ChatApp/Views/Classes/EnrollmentError.cshtml
<hr />
<br />
<br />

<div class="jumbotron">
    <hr />

    <div>

        <h2>
            Dear @ViewBag.StudentName
        </h2>

        <h3 style="color:cornflowerblue">you have been Enrolled in class << @ViewBag.classname >>sometimes ago!></h3>


    </div>

    <hr />
    <hr />



</div>



ChatApp/ChatApp/Views/Classes/FindClassByAccessCode.cshtml
@model Model.Class
    @if (Model.Title == null)
      {

              <script type="text/javascript">
                    alert("کد وارد شده صحیح نمیباشد");
              </script>
      }
else
{
    <html>

    <head>

        <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>


        <script type="text/javascript">
            function searchFaild() {
                $("#searchResult").html("Sorry!!!! Some Error occurred, please try later");
            }
        </script>
        <style>
            #loader {
                display: none;
            }
        </style>


    </head>


    <body>

        <dl class="dl-horizontal">

            <dt id="aaa">
                @Html.DisplayNameFor(model => model.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.University.UniversityTitle)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.University.UniversityTitle)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.MemberCount)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MemberCount)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Semester)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Semester)
            </dd>



            <dt>
                @Html.DisplayNameFor(model => model.AdminInfo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AdminInfo)
            </dd>

            @*<dt>
                    @Ajax.ActionLink("Join", "JoinClass", "Classes",new {ID=Model.ID },
                   new AjaxOptions
                   {
                       HttpMethod = "POST",
                       InsertionMode = InsertionMode.Replace,
                       UpdateTargetId = "res"

                   }
                , new { @class = "btn btn-defualt btn-success" }

                )
                </dt>*@

        </dl>


        <div>

            @Html.ActionLink(Resources.ClassRF.Join_btn, "JoinClass", new { id = Model.ID }, new { @class = "btn btn-default btn-default btn-success btn-lg" }) 


            @*@using (Ajax.BeginForm("JoinClass","Classes",new {classId=Model.ID },new AjaxOptions
                {
                    OnFailure = "searchFaild",

                    InsertionMode = InsertionMode.Replace,
                    HttpMethod = "POST",
                    LoadingElementId = "ajaxloader"

                }))
                {
                <div>
                    <input type="submit" value=" Join !" class="btn btn-primary btn-default" />
                    <img id="loader" src="~/Content/LoadingPic/ajax-loader (1).gif" />
                </div>
                    }*@
        </div>

        <br />
        <hr />

    </body>


</html>

}

ChatApp/ChatApp/Views/Classes/FindUniversity.cshtml
@model Model.Class

@{
    ViewBag.Title = Resources.ClassRF.CreatTitle;
}

<hr />
@using (Html.BeginForm("CreateClass", "Classes", FormMethod.Get))
{
    @Html.AntiForgeryToken()

    <table width="100%" border="0" cellpadding="0" cellspacing="0" class="jumbotron">
        <tr>
            <td height="77" align="center" valign="middle"> <h3>@Resources.ClassRF.SelectUniversity</h3></td>
        </tr>
        <tr>
            <td height="75" align="center" valign="middle">
                <div class="form-group">

                    @Html.DropDownList("UniversityId", null, htmlAttributes: new { @class = "form-control mycombo" })
                    @Html.ValidationMessageFor(model => model.UniversityId, "", new { @class = "text-danger" })

                </div>
            </td>
        </tr>

        <tr>
            <td height="60" align="center" valign="middle">
                <div>
                    <input type="submit" value="@Resources.ClassRF.Ok_btn" class="btn btn-default btn-success btn-lg" style="padding-right:100px;padding-left:100px" />
                </div>
            </td>
        </tr>
        <tr style="height:100px"></tr>
        <tr>
            <td height="92" align="center" valign="middle">
                <p><a class="btn btn-default  btn-lg btn-primary" style="padding-right:200px;padding-left:200px" href="https://localhost:44355/Universities/Create">@Resources.ClassRF.AddUniversity_btn&raquo;</a></p>
                <h5>@Resources.ClassRF.AddUniversity_msg</h5>
            </td>
        </tr>
        <tr>
        </tr>
        <tr>
            <td>&nbsp;</td>
        </tr>
    </table>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ChatApp/ChatApp/Views/Classes/Index.cshtml
@model IEnumerable<Model.Class>

@{
    ViewBag.Title = "Index";
}

<hr />
<p>
    @Html.ActionLink("Create New", "FindUniversity","Classes",null,new { @class = "btn btn-default btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProfileImage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.University.UniversityTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MemberCount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Semester)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccessCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AdminInfo)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        <img src="~/ClassProfileImages/ClaccIcon.jpg" width="35" height="35" style="border-radius:35px" />

    </td>
    <td>
        @Html.DisplayFor(modelItem => item.University.UniversityTitle)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Title)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.MemberCount)

    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Semester)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.AccessCode)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.AdminInfo)
    </td>

    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.ID },new { @class = "btn btn-default btn-primary btn-sm" }) |
        @Html.ActionLink("Details", "Details", new { id = item.ID },new { @class = "btn btn-default btn-success btn-sm" }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.ID },new { @class = "btn btn-default btn-danger btn-sm" })
    </td>
</tr>
}

</table>

ChatApp/ChatApp/Views/Classes/UserSuccesfullyJoined.cshtml
<hr />
<br />
<br />
@{
    int ClassIdretrive = @ViewBag.ClassId;
}


<div class="jumbotron">
    <hr />

    <div>

        <h2>
            Dear @ViewBag.StudentName
        </h2>
        <h2> @ViewBag.classname</h2>
        <h3>    @Resources.ClassRF.Welcome_msg  !></h3>

        <h5>@Resources.ClassRF.lastMemberCount :  @ViewBag.nth  :)</h5>


    </div>

    <hr />
    <hr />

    <div class="row">
        <div class="col-md-5">
            @Html.ActionLink(@Resources.ClassRF.OpenClass, "MyClass", new { classID = ClassIdretrive }, new { @class = "btn btn-success col-md-5" })

        </div>

        <div class="col-md-5" style="align-items:center">
            <p><a class="btn btn-success col-md-5" href="https://localhost:44355/Classes/MyClasses">@Resources.ClassRF.MyClasses</a></p>
        </div>

    </div>



</div>
