ChatApp/ChatApp/Controllers/AccountManagerController.cs
using FormsAuthenticationExtensions;
using Model;
using System;
using System.Collections.Specialized;
using System.IO;
using System.Linq;
using System.Resources;
using System.Web.Mvc;
using System.Web.Security;

namespace ChatApp.Controllers
{
    public class AccountManagerController : Controller
    {
        private ChatAppContext db = new ChatAppContext();

        [HttpGet]
        public ActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("MyClasses", "Classes");
            }
            else
            {
                return View();

            }

        }

        [HttpPost]
        public ActionResult Login(User user, string returnUrl)
        {
            //When user type some Url befor Login,and then directed to Loign Page,"returnUrl" will have some value...
            //but when The User himself press Login Butttomn,this that  will be null,so we redirect user to see his classes!!! 

            user.Password = Encryption.encrypt(user.Password);
            using (ChatAppContext db = new ChatAppContext())
            {
                User u = db.Users.Where(x => x.Username == user.Username && x.Password == user.Password).FirstOrDefault();
                if (u != null)
                {
                    // FormsAuthentication.SetAuthCookie(user.Username,false);

                    //NOTE: I create a new FormsAuthenticationCookie intead of useing "AuthCookie" To Store additional data 
                    //in order to have username & userRoleId in all over the Project!

                    var ticketData = new NameValueCollection
                       {
                             { "UserID", u.ID.ToString() },
                             { "UserRoleId", u.RoleId.ToString() }
                       };
                    new FormsAuthentication().SetAuthCookie(u.Username, true, ticketData);

                    //declare a cookie for admin inorder to make difference in layout for him:
                    if (u.RoleId==1010)
                    {
                        Response.Cookies["adminCookie"].Value = "admin";

                    }


                    //Status field show that the whether the user is online or offline !
                    u.Status = true;
                    //save profile url in coocki:
                    
                    if (u.ProfileImage != null)
                    {
                        string cookieTitle = u.Username;
                        Response.Cookies[cookieTitle].Value = u.ProfileImage;
                   
                    }



                    if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/") && !returnUrl.StartsWith("//")
                        && !returnUrl.StartsWith("/\\"))
                    {
                        return Redirect(returnUrl);
                    }

                    else
                    {
                        return RedirectToAction("MyClasses", "Classes");
                    }

                }
                else
                {
                    ModelState.AddModelError(string.Empty, "!نام کاربری یا رمز عبور اشتباه است");
                    ModelState.Clear();
                    return View();

                }
            }



        }



        //^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        public ActionResult SignUp()
        {
            //return RedirectToAction("Create", "Users");
            ViewBag.RoleId = new SelectList(db.Roles, "ID", "RoleName");
            return View();

        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp(AddEditUserViewmodel model)
        {

            if (ModelState.IsValid)
            {
                
               
                    //recive uploaded file as the profile image:
                    if (model.ImageFile!=null)
                    {
                        try
                        {
                            string filename = Path.GetFileNameWithoutExtension(model.ImageFile.FileName);
                            string extention = Path.GetExtension(model.ImageFile.FileName);
                            filename = filename + DateTime.Now.ToString("yymmssfff") + extention;
                            model.ImagePath = "~/UserProfileImage/" + filename;
                            filename = Path.Combine(Server.MapPath("~/UserProfileImage/"), filename);
                            model.ImageFile.SaveAs(filename);

                            model.UserViewModel.ProfileImage = model.ImagePath;
                        }
                        catch (Exception)
                        {
                            ModelState.AddModelError(string.Empty, "آپلود عکس با مشکل مواجه شده است.لطفا مجددا تلاش کنید");
                            return View(model);
                        }
                        
                    }
                model.UserViewModel.ID = Guid.NewGuid();
                //Encrypting password:
                string EncryptedPassword = Encryption.encrypt(model.UserViewModel.Password);
                model.UserViewModel.Password = EncryptedPassword;
                //Encrypting ConfirmPassword:
                string EncryptedCOnfirmPassword = Encryption.encrypt(model.UserViewModel.Confirmation);
                model.UserViewModel.Confirmation = EncryptedCOnfirmPassword;


                try
                {
                    db.Users.Add(model.UserViewModel);
                    db.SaveChanges();
                    return RedirectToAction("Login");
                }
                catch (Exception)
                {

                    ModelState.AddModelError(string.Empty, "ثبت نام شما در سامانه با خطا مواجه شده.لطفا مجددا اقدام کنید");
                }
                

            }

            ViewBag.RoleId = new SelectList(db.Roles, "ID", "RoleName", model.UserViewModel.RoleId);
            return View(model);

        }


        public ActionResult SignOut()
        {
            //ایا کاربر میتواند اکانت خودش را حذف کند؟؟؟؟؟؟
            return View();
        }


        public ActionResult LogOut()
        {
            // set user status :offline! 
            //{
            var ticketData = ((FormsIdentity)HttpContext.User.Identity).Ticket.GetStructuredUserData();
            string userid = ticketData["UserID"];
            ClassesController c = new ClassesController();
            User u = c.FindUserById(Guid.Parse(userid));
            u.Status = false;
            //}
            //destroy Admin Cookie:
            if (Request.Cookies["adminCookie"] != null)
            {
                Response.Cookies["adminCookie"].Expires = DateTime.Now.AddDays(-1);
            }

            //destroy Profile Cookie:
            if (Request.Cookies["ProfileImage"] != null)
            {
                Response.Cookies["ProfileImage"].Expires = DateTime.Now.AddDays(-1);
            }

            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }



        public ActionResult NiceLoginPage()
        {
            return View();
        }


       
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }








    }
}

ChatApp/ChatApp/Controllers/UsersController.cs
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Resources;
using System.Web.Mvc;
using System.Web.Security;
using ChatApp.Filter;
using FormsAuthenticationExtensions;
using Model;

namespace ChatApp.Controllers
{
    [Authorize]
    [NitishAuthentication]

    public class UsersController : Controller
    {
        private ChatAppContext db = new ChatAppContext();

        [Authorize(Roles="Admin")]
        public ActionResult Index()
        {
            var users = db.Users.Include(u => u.Role);
            return View(users.ToList());
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

 
        //public ActionResult Create()
        //{
        //    ViewBag.RoleId = new SelectList(db.Roles, "ID", "RoleName");
        //    return View();
        //}

        //// POST: Users/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ID,Firstname,Lastname,Username,Password,ProfileImage,Status,EmailAddress,PhoneNumber,RoleId,Confirmation")] User user)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        user.ID = Guid.NewGuid();
        //        //Encrypting password:
        //        string EncryptedPassword =Encryption.encrypt(user.Password);
        //        user.Password = EncryptedPassword;
        //        //Encrypting ConfirmPassword:
        //        string EncryptedCOnfirmPassword = Encryption.encrypt(user.Confirmation);
        //        user.Confirmation= EncryptedCOnfirmPassword;

        //        db.Users.Add(user);
        //        db.SaveChanges();
        //        return RedirectToAction("Login");
        //    }

        //    ViewBag.RoleId = new SelectList(db.Roles, "ID", "RoleName", user.RoleId);
        //    return View(user);
            
        //}


        //Edit Method has been changed...
        //beacase only Authenticated Users can access this action,and every one can change his own Info
        //So that Edit methode DOES NOT need take id in parameters!

        //public ActionResult Edit(Guid? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    User user = db.Users.Find(id);
        //    if (user == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.RoleId = new SelectList(db.Roles, "ID", "RoleName", user.RoleId);
        //    return View(user);
        //}

        public ActionResult Edit()
        {
            var ticketData = ((FormsIdentity)HttpContext.User.Identity).Ticket.GetStructuredUserData();
            string usrid = ticketData["UserID"];
            var id = Guid.Parse(usrid);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            //ViewBag.RoleId = new SelectList(db.Roles, "ID", "RoleName", user.RoleId);
            Model.AddEditUserViewmodel vm = new AddEditUserViewmodel();
            vm.UserViewModel = user;
           
            return View(vm);
        }


        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Model.AddEditUserViewmodel model)
        {
            if (ModelState.IsValid)
            {
                //Check wether User has Change his ProfileImage OR not??  :
                if (model.ImageFile !=null )
                {

                    //deleting current profileimage from folder:
                    string filePath = Server.MapPath(model.UserViewModel.ProfileImage);
                    if (System.IO.File.Exists(filePath))
                          System.IO.File.Delete(filePath);

                    //seve new profile Imag:
                    string filename = Path.GetFileNameWithoutExtension(model.ImageFile.FileName);
                    string extention = Path.GetExtension(model.ImageFile.FileName);
                    filename = filename + DateTime.Now.ToString("yymmssfff") + extention;
                    model.ImagePath = "~/UserProfileImage/" + filename; ;
                    filename = Path.Combine(Server.MapPath("~/UserProfileImage/"), filename);
                    model.ImageFile.SaveAs(filename);
                    model.UserViewModel.ProfileImage = model.ImagePath;

                    //Update profile Image on the header :

                        string cookieTitle = model.UserViewModel.Username;
                        Response.Cookies[cookieTitle].Value = model.ImagePath;

                    
                }

                try
                {
                    //Edit Statments goes here:
                    db.Entry(model.UserViewModel).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("MyClasses", "Classes");
                }
                catch (Exception)
                {
                    ModelState.AddModelError(string.Empty, "ویرایش اطلاعات با خطا مواجه شده است.ممکن است حجم عکس شما بیشتر از 2 مگابایت باشد.دوباره تلاش کنید");
                    return View(model);
                }
               
            }
            return View(model);

        }









        //=Delete Account

        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        //****************************************************************************
        //****************************************************************************
        public User FindUserById(Guid? id)
        {
            if (id == null)
                  return null;

            User user = db.Users.Find(id);

            if (user == null)
                  return null;


            return user;
        }


      

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

       
    }
}

ChatApp/ChatApp/Views/Shared/Error404.cshtml

<head>
    <link href="~/Content/Error401.css" rel="stylesheet" />
</head>
<body>

    <div id='error-page'>
        <div id='error-inner'>
            <hr />
            <br />

            <h1> The page you are looking for might have been removed, had its name changed or is temporarily unavailable</h1>
            <div class="pesan-eror">404</div>
            <div class="container">
                <p class="balik-home">Back to Home, your handsome dad here!</p>

            </div>
        </div>
    </div>
</body>

ChatApp/ChatApp/Views/Shared/UnAuthorizeErrorPage.cshtml
<head>
    <link href="~/Content/Error401.css" rel="stylesheet" />

</head>
<body>

   <br />
    <br />
    <br />


    <div>
        <div id='error-page'>
            <div id='error-inner'>
                <br/>
                <br />

                <h1>  ! Sorry ! </h1>
                <h3>But you are NOT authorize to see this page</h3>
                <br />
                <div class="pesan-eror">401</div>
                <br />

                <p class="balik-home"><a href="https://localhost:44355/Home">Back to Home</a></p><br />
            </div>
        </div>
    </div>
</body>

ChatApp/ChatApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="@Url.Content("~/Content/myCss.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="~/Content/CustomCss.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>

    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/MicrosoftAjax.js"></script>
    <script src="~/Scripts/MicrosoftMvcAjax.js"></script>



    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

    @*Login PAge Desine :*@
 @*   <link href="~/Content/LoginPage.css" rel="stylesheet" />
    <script src="~/Scripts/LoginPage.js"></script>
     *@


    <title>@ViewBag.Title - ChatApp</title>
    @if (System.Globalization.CultureInfo.CurrentCulture.Name.Contains("fa"))
    {
        <link href="@Url.Content("~/Content/bootstrap.rtl.css")" rel="stylesheet" type="text/css" />      
    }
    else
    {
        @Styles.Render("~/Content/css")

    }
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <nav style="position:relative">
            <div dir="ltr">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Chat App", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>

                <ul class="navbar-btn nav navbar-nav">
                    <li>@Html.ActionLink(ChatApp.App_GlobalResources.Global.Home, "Index", "Home")</li>
                    <li>@Html.ActionLink(ChatApp.App_GlobalResources.Global.About, "About", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> @Resources.Global.Language <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("English", "ChangeLanguage", "Home", new { lan = "en-US" }, null)</li>
                            <li> @Html.ActionLink("فارسی", "ChangeLanguage", "Home", new { lan = "fa-IR" }, null)</li>
                        </ul>
                    </li>
                    @if (User.Identity.IsAuthenticated && Request.Cookies["adminCookie"] != null && Request.Cookies["adminCookie"].Value.ToString() == "admin")
                    {

                        <li>@Html.ActionLink(ChatApp.App_GlobalResources.Global.ClassesList, "Index", "Classes")</li>
                        <li>@Html.ActionLink(ChatApp.App_GlobalResources.Global.UsersList, "Index", "Users")</li>


                    }



                </ul>



            </div>

            @if (System.Globalization.CultureInfo.CurrentCulture.Name.Contains("fa"))
            {
                <div class="fixLeft">
                    <ul class="navbar-btn nav navbar-nav">
                        <li>
                            @Html.ActionLink(Resources.Global.SignUp, "SignUp", "AccountManager")
                        </li>

                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li>
                                @Html.ActionLink(Resources.Global.Login, "Login", "AccountManager")
                            </li>
                        }
                        else
                        {
                            <li>
                                @Html.ActionLink(Resources.Global.Logout, "LogOut", "AccountManager")
                            </li>
                            string cookieName = User.Identity.Name;
                            if (Request.Cookies[cookieName] != null)
                            {
                                <li>
                                    <div>
                                        <a href="https://localhost:44355/Users/Edit" style="margin:auto" >
                                            <img src="@Url.Content(Request.Cookies[cookieName].Value.ToString())" alt="@User.Identity.Name" title="  @User.Identity.Name  " width="50" height="50" style="border-radius:50px" />
                                        </a>
                                    </div>
                                </li>
                            }
                            else
                            {
                                <li>
                                    <div>
                                        <a href="https://localhost:44355/Users/Edit" style="padding-right:30%">
                                            <img src="~/UserProfileImage/Profile.png" alt="my img" width="30" height="30" style="border-radius:20px" />
                                        </a>
                                        <span style=" color:cornsilk; padding-top:3px;padding-bottom:0px">@User.Identity.Name</span>
                                    </div>
                                </li>
                            }



                        }



                    </ul>
                </div>
            }
            else
            {
                <div class="fixRight">
                    <ul class="navbar-btn nav navbar-nav">
                        <li>
                            @Html.ActionLink(Resources.Global.SignUp, "SignUp", "AccountManager")
                        </li>

                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li>
                                @Html.ActionLink(Resources.Global.Login, "Login", "AccountManager")
                            </li>
                        }
                        else
                        {
                            <li>
                                @Html.ActionLink(Resources.Global.Logout, "LogOut", "AccountManager")
                            </li>
                            string cookieName = User.Identity.Name;
                            if (Request.Cookies[cookieName] != null)
                            {
                                <li>
                                    <div>
                                        <a href="https://localhost:44355/Users/Edit" style="margin:auto">
                                            <img src="@Url.Content(Request.Cookies[cookieName].Value.ToString())" alt="@User.Identity.Name" title="  @User.Identity.Name  " width="50" height="50" style="border-radius:50px" />
                                        </a>
                                    </div>
                                </li>
                            }
                            else
                            {
                                <li>
                                    <div>
                                        <a href="https://localhost:44355/Users/Edit" style="padding-right:30%">
                                            <img src="~/UserProfileImage/Profile.png" alt="my img" width="30" height="30" style="border-radius:20px" />
                                        </a>
                                        <span style=" color:cornsilk; padding-top:3px;padding-bottom:0px">@User.Identity.Name</span>
                                    </div>
                                </li>
                            }



                        }





                    </ul>
                </div>
            }


        </nav>
        
    </div>



    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ChatApp</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>